#include <msp430.h>


//Pines
#define ACCEL_CS_BIT BIT5 //CS P3.5
#define ACCEL_SIMO_BIT BIT3 //SIMO P3.3
#define ACCEL_INT_BIT BIT5 //INT P2.5
#define ACCEL_SCK_BIT BIT7 //SCK P2.7
#define ACCEL_PWR_BIT BIT6 //PWR P3.6
#define ACCEL_SOMI_BIT BIT4 //SOMI P3.4

//Puertos

#define ACCEL_CS_OUT P3OUT
#define ACCEL_CS_SEL P3SEL
#define ACCEL_CS_DIR P3DIR

#define ACCEL_SIMO_OUT P3OUT
#define ACCEL_SIMO_SEL P3SEL
#define ACCEL_SIMO_DIR P3DIR

#define ACCEL_INT_OUT P2OUT
#define ACCEL_INT_SEL P2SEL
#define ACCEL_INT_DIR P2DIR

#define ACCEL_SCK_OUT P2OUT
#define ACCEL_SCK_SEL P2SEL
#define ACCEL_SCK_DIR P2DIR

#define ACCEL_PWR_OUT P3OUT
#define ACCEL_PWR_SEL P3SEL
#define ACCEL_PWR_DIR P3DIR

#define ACCEL_SOMI_OUT P3OUT
#define ACCEL_SOMI_SEL P3SEL
#define ACCEL_SOMI_DIR P3DIR


void accel_init() {



    //Power on

}
